name: Deploy MkDocs

on:
  push:
    branches:
      - main  # 當 main 分支有 push 時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # 可調整 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Configure Git to use PAT
        env:
          PAT_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git

      - name: Build and deploy MkDocs
        run: |
          mkdocs gh-deploy --force --clean --remote-name origin --remote-branch gh-pages
